### ISSUE TITLE
Landing rate in Cessna Skyhawk

### ISSUE THREAD

**Issue by lsnewman** [scelts/msfslandingrate#9]
I'm getting landing rates of 200ft + in the cessna skyhawk even when it's super smooth.

**Comment by scelts** [comment]
Can you give me a bit more information:

- Which version it is?
- If it's 1.0.0 did it work well in the previous?
- Is it only that you get the too high landing rates, or you also smack sometimes the plane, and get the low landing rate?
- Is it always, or you do the two same smooth landings, and one is high landing rate, another low.
- What's the G force?
- Is it the same for the other planes or just skyhawk?

And also a general one, sorry for asking, but the issue is very vague, so I have to ask. How many years of flight, or fligt-sim experience you have? To what are you comparing the smooth landing?

And finally, as the version 1.0.0 takes the landing rate straight from the sim, instead of calculating it, and it should be the same as in landing challenges. Do you see the difference if you do a landing challenge with cessna, between the two?

**Comment by lsnewman** [comment]
Hi,

Version 1.0.0.
Didn't try it prior.
Only high, haven't tried hard landing.
Just the skyhawk.

However: I'll be frank, I never fly GA so I could just be really bad at it, and I had been using slew just prior so that may have sped the aircraft up way higher than I noticed?

I haven't had any issues since, especially in the a320neo which I normally use. 

It's probably user error, so I'll mark closed.

Cheers.

**Comment by scelts** [comment]
No problem. Before 1.0.0 it could be that the FPM algorithm messes up in case of the low fpm, (or taildraggers). Now, I just read it as MSFS has calculated it, and can't do much.

Sim tip: Don't focus too much on the FPM. It's a bull***t value really. Try to keep the plane going straight (de-crab) and don't smack it completely, and the landing is good.
For example, with a cessna... Sidewind, fpm of -30 and a crab angle of 15-20% on touchdown. That's a horrible landing in real life, you might be smooth but the plane's gonna go all around the runway, you might damage the gear, and the passengers are gonna boo you much more than if you bumped a bit more on the landing but went straight.
